"""payments_table

Revision ID: 09a447c23e72
Revises: 38c3d8c2ee81
Create Date: 2026-04-30 09:02:20.645565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '09a447c23e72'
down_revision: Union[str, Sequence[str], None] = '38c3d8c2ee81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            CREATE TYPE paymentstatus AS ENUM ('TOP_UP', 'DEBIT');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END
        $$;
        """
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column(
        'status',
        postgresql.ENUM('TOP_UP', 'DEBIT', name='paymentstatus', create_type=False),
        nullable=False
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.execute("DROP TYPE IF EXISTS paymentstatus")
    # ### end Alembic commands ###
