"""int uuid

Revision ID: 3fc053e997c9
Revises: b77ab45edfe6
Create Date: 2026-04-25 11:42:08.255704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc053e997c9'
down_revision: Union[str, Sequence[str], None] = 'b77ab45edfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # UUID values were previously derived from integers using:
    #   lpad(to_hex(id), 32, '0')::uuid
    # Reverse by taking the last 8 hex chars and casting to int.
    int_from_uuid = "('x' || right(replace(%s::text, '-', ''), 8))::bit(32)::int"

    # Drop dependent FKs before type changes
    op.drop_constraint(op.f("products_created_by_id_fkey"), "products", type_="foreignkey")
    op.drop_constraint(op.f("cart_items_user_id_fkey"), "cart_items", type_="foreignkey")
    op.drop_constraint(op.f("cart_items_product_id_fkey"), "cart_items", type_="foreignkey")
    op.drop_constraint(op.f("orders_user_id_fkey"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("order_items_product_id_fkey"), "order_items", type_="foreignkey")
    op.drop_constraint(op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey")

    # PKs: users.id, products.id -> INTEGER + identity
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute(
        f"ALTER TABLE users ALTER COLUMN id TYPE INTEGER USING {int_from_uuid % 'id'}"
    )
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('users','id'), GREATEST(mx, 1), mx > 0) "
        "FROM (SELECT COALESCE(MAX(id), 0) AS mx FROM users) s"
    )

    op.execute("ALTER TABLE products ALTER COLUMN id DROP DEFAULT")
    op.execute(
        f"ALTER TABLE products ALTER COLUMN id TYPE INTEGER USING {int_from_uuid % 'id'}"
    )
    op.execute("ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('products','id'), GREATEST(mx, 1), mx > 0) "
        "FROM (SELECT COALESCE(MAX(id), 0) AS mx FROM products) s"
    )

    # FK columns -> INTEGER
    op.execute(
        f"ALTER TABLE products ALTER COLUMN created_by_id TYPE INTEGER USING {int_from_uuid % 'created_by_id'}"
    )
    op.execute(
        f"ALTER TABLE cart_items ALTER COLUMN user_id TYPE INTEGER USING {int_from_uuid % 'user_id'}"
    )
    op.execute(
        f"ALTER TABLE cart_items ALTER COLUMN product_id TYPE INTEGER USING {int_from_uuid % 'product_id'}"
    )
    op.execute(
        f"ALTER TABLE orders ALTER COLUMN user_id TYPE INTEGER USING {int_from_uuid % 'user_id'}"
    )
    op.execute(
        f"ALTER TABLE refresh_tokens ALTER COLUMN user_id TYPE INTEGER USING {int_from_uuid % 'user_id'}"
    )

    # order_items.product_id uses ON DELETE SET NULL -> must be nullable
    op.execute("ALTER TABLE order_items ALTER COLUMN product_id DROP NOT NULL")
    op.execute(
        f"ALTER TABLE order_items ALTER COLUMN product_id TYPE INTEGER USING {int_from_uuid % 'product_id'}"
    )

    # Recreate constraints
    op.create_foreign_key(
        op.f("products_created_by_id_fkey"),
        "products",
        "users",
        ["created_by_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("cart_items_user_id_fkey"),
        "cart_items",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("cart_items_product_id_fkey"),
        "cart_items",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("orders_user_id_fkey"),
        "orders",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("order_items_product_id_fkey"),
        "order_items",
        "products",
        ["product_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    uuid_from_int = "lpad(to_hex(%s), 32, '0')::uuid"

    op.drop_constraint(op.f("products_created_by_id_fkey"), "products", type_="foreignkey")
    op.drop_constraint(op.f("cart_items_user_id_fkey"), "cart_items", type_="foreignkey")
    op.drop_constraint(op.f("cart_items_product_id_fkey"), "cart_items", type_="foreignkey")
    op.drop_constraint(op.f("orders_user_id_fkey"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("order_items_product_id_fkey"), "order_items", type_="foreignkey")
    op.drop_constraint(op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey")

    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute(
        f"ALTER TABLE users ALTER COLUMN id TYPE UUID USING {uuid_from_int % 'id'}"
    )

    op.execute("ALTER TABLE products ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE products ALTER COLUMN id DROP DEFAULT")
    op.execute(
        f"ALTER TABLE products ALTER COLUMN id TYPE UUID USING {uuid_from_int % 'id'}"
    )

    op.execute(
        f"ALTER TABLE products ALTER COLUMN created_by_id TYPE UUID USING {uuid_from_int % 'created_by_id'}"
    )
    op.execute(
        f"ALTER TABLE cart_items ALTER COLUMN user_id TYPE UUID USING {uuid_from_int % 'user_id'}"
    )
    op.execute(
        f"ALTER TABLE cart_items ALTER COLUMN product_id TYPE UUID USING {uuid_from_int % 'product_id'}"
    )
    op.execute(
        f"ALTER TABLE orders ALTER COLUMN user_id TYPE UUID USING {uuid_from_int % 'user_id'}"
    )
    op.execute(
        f"ALTER TABLE refresh_tokens ALTER COLUMN user_id TYPE UUID USING {uuid_from_int % 'user_id'}"
    )

    op.execute(
        f"ALTER TABLE order_items ALTER COLUMN product_id TYPE UUID USING {uuid_from_int % 'product_id'}"
    )
    op.execute("ALTER TABLE order_items ALTER COLUMN product_id SET NOT NULL")

    op.create_foreign_key(
        op.f("products_created_by_id_fkey"),
        "products",
        "users",
        ["created_by_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("cart_items_user_id_fkey"),
        "cart_items",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("cart_items_product_id_fkey"),
        "cart_items",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("orders_user_id_fkey"),
        "orders",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("order_items_product_id_fkey"),
        "order_items",
        "products",
        ["product_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
