"""int -> uuid

Revision ID: b77ab45edfe6
Revises: f74878916e2c
Create Date: 2026-04-24 19:45:57.607824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77ab45edfe6'
down_revision: Union[str, Sequence[str], None] = 'f74878916e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('products_created_by_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')

    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE products ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN id DROP DEFAULT")

    op.alter_column(
        'users',
        'id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(id), 32, '0')::uuid",
    )
    op.alter_column(
        'products',
        'id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(id), 32, '0')::uuid",
    )
    op.alter_column(
        'products',
        'created_by_id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(created_by_id), 32, '0')::uuid",
    )
    op.alter_column(
        'refresh_tokens',
        'id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(id), 32, '0')::uuid",
    )
    op.alter_column(
        'refresh_tokens',
        'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(user_id), 32, '0')::uuid",
    )
    op.alter_column(
        'orders',
        'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(user_id), 32, '0')::uuid",
    )
    op.alter_column(
        'cart_items',
        'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(user_id), 32, '0')::uuid",
    )
    op.alter_column(
        'cart_items',
        'product_id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(product_id), 32, '0')::uuid",
    )
    op.alter_column(
        'order_items',
        'product_id',
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="lpad(to_hex(product_id), 32, '0')::uuid",
    )

    op.create_foreign_key(
        op.f('products_created_by_id_fkey'),
        'products',
        'users',
        ['created_by_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        op.f('refresh_tokens_user_id_fkey'),
        'refresh_tokens',
        'users',
        ['user_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('orders_user_id_fkey'),
        'orders',
        'users',
        ['user_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    op.create_foreign_key(
        op.f('cart_items_user_id_fkey'),
        'cart_items',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        op.f('cart_items_product_id_fkey'),
        'cart_items',
        'products',
        ['product_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        op.f('order_items_product_id_fkey'),
        'order_items',
        'products',
        ['product_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('products_created_by_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')

    op.alter_column(
        'order_items',
        'product_id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(product_id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'cart_items',
        'product_id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(product_id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'cart_items',
        'user_id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(user_id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'orders',
        'user_id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(user_id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'refresh_tokens',
        'user_id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(user_id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'refresh_tokens',
        'id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'products',
        'created_by_id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(created_by_id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'products',
        'id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(id::text, '-', ''), 8))::bit(32)::int",
    )
    op.alter_column(
        'users',
        'id',
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="('x' || right(replace(id::text, '-', ''), 8))::bit(32)::int",
    )

    op.create_foreign_key(op.f('products_created_by_id_fkey'), 'products', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
